import Foundation
import LocalLLMClientCore

#if BUILD_DOCC
@preconcurrency @_implementationOnly import llama
#elseif canImport(llama)
@preconcurrency private import llama
#else
@preconcurrency import LocalLLMClientLlamaC
#endif

/// A utility to parse tool calls from a response generated by a model using llama.cpp's common_chat_parse
struct LlamaToolCallParser {
    /// Parses a string for tool calls using the parser context derived from the model's chat template.
    ///
    /// - Parameters:
    ///   - response: The string to parse for tool calls
    ///   - chatParams: Pointer to the model-owned `llm_chat_params` (obtained via `Model.chatParams()`).
    /// - Returns: An array of LLMToolCall objects if any were found, otherwise nil
    public static func parseToolCalls(from response: String, chatParams: UnsafeMutablePointer<llm_chat_params>?) -> [LLMToolCall]? {
        guard let chatParams else { return nil }

        let parsedMessage = response.withCString { cstr in
            parse_chat_response(chatParams, cstr, false)
        }
        guard !parsedMessage.tool_calls.empty() else {
            return nil
        }

        var toolCalls: [LLMToolCall] = []
        for i in 0..<parsedMessage.tool_calls.size() {
            let cppToolCall = parsedMessage.tool_calls[i]

            let id = cppToolCall.id.empty() ? UUID().uuidString : String(cppToolCall.id)
            let name = String(cppToolCall.name)
            let arguments = String(cppToolCall.arguments)

            toolCalls.append(LLMToolCall(id: id, name: name, arguments: arguments))
        }

        return toolCalls.isEmpty ? nil : toolCalls
    }
}
